# 何时使用 panic

### 概述

- 一旦 ```panic!``` ，则程序无法恢复
- 而返回 ```Result``` 时，调用者可以自行决定是否 ```panic!```
- 因此在定义函数时，使用 ```Result``` 是更好的选择，将决定权交给调用者
- 但是在某些情况下，```panic!``` 更合适：Examples / Prototype Code / Tests

### 使用 ```panic!``` 的场景

##### Examples

- 编写示例代码来展示某些概念时，健壮的错误处理反而会导致代码不够清晰
- 在示例代码中，类似 ```unwrap``` 这种可能导致 panic 的调用，更适合也更易于用来表达此处需要进行错误处理，而不用也不应该加入更多健壮的错误处理代码去影响示例代码的可读性

##### Prototype Code

- 原型开发时，在决定如何处理错误情况之前，可以使用 ```unwrap``` 、 ```expect``` 等等这些非常便利的方法
- 以后准备处理这些错误情况时，这些方法在代码中都是很清晰的标识

##### Tests

- 在测试时，如果一个方法调用失败了，可以让整个测试失败并终止，虽然这个方法并不是测试的功能点
- 因为在测试时，```panic!```可以标记出测试是如何失败的，所以通过 ```unwrap``` 、 ```expect``` 等，可以让测试精确的表现出其结果

##### Wiser than Compiler

- 虽然得到的是 ```Result``` ，但程序员确定结果不可能是 ```Err```，此时就可以直接使用 ```unwrap```
- 这个时候程序员就比编译器更聪明，因为编译器无法知道此时结果一定不可能 ```Err```
- 例如下面的例子，可以直接使用 ```unwrap```

```rust
use std::net::IpAddr;

/*
需要注意的是，
若此时字符串不是硬编码，
而是根据用户输入的话，
就需要明确的处理 Err 的情况
*/
let home: IpAddr = "127.0.0.1".parse().unwrap();
```

### ++Guidelines++ for ```panic！```

##### panic 使用原则：

1. 代码可能因为 bad state 而终止
2. 出现了非预期的 bad state
3. 后续代码的执行取决于 bad state 没有出现
4. 对于所使用的 types ，无法 encode 该 bad state 信息

##### bad state 解释：

- 一些规则（assumption/guarantee/contract/invariant）被打破
- 例如，无效的值，矛盾的值，不存在的值

##### bad state 举例：

调用代码时：
- 你的代码调用外部代码时
- 这些外部代码不在可控范围
- 外部代码返回了无效的状态
- 因此你的代码无法处理和修复这种无效状态
- 此时适合使用 ```panic!```

代码被调用时：
- 你的代码被调用时
- 传入了无意义的值
- 此时最好的方式是 ```panic!```
- 从而告诉调用者这是一个 bug
- 进而调用者在开发阶段即可修复该 bug

处理数据时：
- 首先，对数据进行有效性校验
- 其次，若数据无效，则 ```panic!```
- 这是出于安全性考虑，因为尝试操作无效数据会使代码出现安全漏洞
- 这就是标准库在发生越界内存访问(例如数组)时 ```panic!``` 的主要原因，尝试访问不属于当前数据结构的内存，是一种常见的引发安全问题的行为

违反函数契约时：
- 函数通常都有契约
- 也就是说，函数的行为只有在输入的信息满足特定要求时才能得到保证
- 违反契约时，```panic!``` 是有意义的，因为这是调用者的 bug，而不是一种你希望调用者在外部来处理的错误，且事实上，调用者也没有合理的方式来处理这种错误，因为调用者需要做的是修复其代码

> 注意：函数的契约，尤其对于违反后会导致 panic 的契约，应当在 API 文档中注明

### ++Guidelines++ for ```Result```

- 预期的错误发生时，适合使用 ```Result``` 而不是 ```panic!```
- 例如，parser 接收到格式不正确的数据
- 又如，HTTP 请求遇到限流的情况
- 对于这些场景，返回 ```Result``` 表示某些预期的失败情况会发生，并让调用者来决定如何处理

### 借助 Rust 的类型系统

##### 类型系统的作用

- 如果在所有的函数中都进行大量的错误校验和检查，会导致代码非常冗余
- 因此，可以借助 Rust 的类型系统来做这些工作，也就是说，通过编译器来进行类型检查
- 如果函数参数是一种特殊的类型，那么在代码逻辑中，可以假定编译器已经确保了该参数一定是有效的值
- 例如，参数类型不是 ```Option``` ，且程序希望该参数的值是 something 而不是 nothing，那么，代码中不需要处理 ```Some``` 和 ```None``` 这两种情形，因为只有一种情况，就是该参数会确切的有一个值。当传入 nothing 时，编译器就会报错，所以在运行时，代码也就没必要检查 nothing 这种情况
- 又如，参数使用 u32 类型，则可以确保接收到的值不会为负数

##### 自定义类型

假设在函数中，我们希望某个参数的值范围在 1-100 以内，那么我们会做如下检查和处理：
```rust
if guess < 1 || guess > 100 {
}
else {
}
```

但是，这种处理方式存在一些问题：
- 如果函数只能处理 1-100 的这个特性很关键
- 而且如果存在很多函数都是要求这个特性
- 那么，在每个函数中都进行这样的检查会让代码非常冗余，甚至可能会影响程序的性能

因此，可以自定义一个类型，并使用类型检查：

```rust
pub struct Guess {
    value: i32,
}

impl Guess {
    pub fn new(value: i32) -> Guess {
        if value < 1 || value > 100 {
            panic!("invalid value");
        }

        Guess {
            value
        }
    }

    pub fn value(&self) -> i32 {
        self.value
    }
}
```

剖析：
1. 定义了 ```Guess``` 这个 struct 类型，并通过它来存储 ```i32``` 的 ```value```
2. 定义 ```new``` 方法来创建 ```Guess``` 实例
3. 在 ```new``` 方法中，若数值不合法，则程序 ```panic!``` ，因为所传入的值违反了该函数的契约，并告知调用者需要修复该 bug ；否则创建 ```Guess``` 并返回
4. 在 API 文档中，需要描述这种可能导致 panic 的情况，在 Chapter14 中讨论
5. 定义 ```value``` 方法来返回该数值，这种方法就是 *getter*
6. 为 ```value``` 方法加上 pub 修饰是必须的，因为 struct 中 ```value``` 这个 field 是 private
7. 让 ```value``` 这个 field 作为 private 成员是很重要的：外部使用者不能直接设置该值，而且只能通过 ```new``` 方法来创建 ```Guess``` 实例，进而也就确保了 ```Guess``` 中的值是被检查过的
8. 因此，当一个函数的参数或返回值要求在 1-100 之间时，就使用 ```Guess``` 类型而不是 ```i32``` 类型，这样在代码中就不再需要额外的错误检查

### 总结

- Rust 的错误处理机制可以帮助代码变得健壮
- ```panic!``` 表示程序遇到了无法处理的 state ，因此程序终止，而不是继续尝试处理无效或不正确的数据
- ```Result``` 表示在某些情形下，操作可能会失败，且代码需要处理这种失败的情况，因此，可以使用 ```Result``` 来告知调用者需要同时处理成功和失败的情况
